# Generated by Django 6.0.7 on 2026-07-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_adminsetting_banner_coupon_kitchen_kitchencategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
