# Generated by Django 4.2.30 on 2026-08-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_is_verified_to_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymenu',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='is_veg',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='meal_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='business_hours',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='fssai_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='id_proof_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='is_veg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='license_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='specialties',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='inclusions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_veg',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allergies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dietary_preferences',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
