# Generated by Django 4.2.30 on 2026-08-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_dailymenu_description_dailymenu_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_otp',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
