# Generated by Django 5.2.17 on 2026-08-24 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_order_delivery_time_order_order_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutrequest',
            name='delivery_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_payout_requests', to='api.userprofile'),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='chef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to='api.userprofile'),
        ),
    ]
