# Generated by Django 5.2.17 on 2026-09-06 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_userprofile_current_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoicePin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_hash', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_pin', to='api.userprofile')),
            ],
            options={
                'db_table': 'voice_pins',
            },
        ),
        migrations.CreateModel(
            name='VoiceAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_consumed', models.BooleanField(default=False)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_authorizations', to='api.userprofile')),
            ],
            options={
                'db_table': 'voice_authorizations',
                'indexes': [models.Index(fields=['user', 'is_consumed'], name='voice_autho_user_id_c6899b_idx'), models.Index(fields=['token'], name='voice_autho_token_981cbc_idx')],
            },
        ),
    ]
