# Generated by Django 5.2.17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_voicepin_voiceauthorization'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='eta_5min_notified',
            field=models.BooleanField(default=False),
        ),
    ]
