# Generated by Django 5.2.17 on 2026-09-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_order_delivery_latitude_order_delivery_longitude_order_eta_5min_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='order',
            name='plan',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('one_time', 'One-Time Order')], default='one_time', max_length=20),
        ),
        migrations.DeleteModel(
            name='DailyMenu',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
