# Generated by Django 5.2.17 on 2026-09-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_subscriptionplan_kitchen_remove_order_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='preparation_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('ready_for_delivery', 'Ready for Delivery'), ('assigned', 'Assigned'), ('picked_up', 'Picked Up'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
