databases:
  - name: mealin-db
    plan: free
    databaseName: mealin
    user: mealin

services:
  - type: web
    name: mealin-api
    runtime: python
    rootDir: backend
    buildCommand: bash build.sh
    startCommand: python manage.py migrate --noinput && python manage.py create_admin && gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mealin-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: BREVO_SMTP_HOST
        value: "smtp-relay.brevo.com"
      - key: BREVO_SMTP_PORT
        value: "587"
      - key: BREVO_SMTP_TLS
        value: "True"
      - key: BREVO_SMTP_USER
        sync: false
      - key: BREVO_SMTP_PASSWORD
        sync: false
      - key: BREVO_SENDER_EMAIL
        value: "sachins43270@gmail.com"
      - key: BREVO_SENDER_NAME
        value: "Housefoods"
      - key: BREVO_API_KEY
        sync: false
