// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB64NBYxaSapj8R7a56yV7e6S0MUJIgZYs',
    appId: '1:481479523905:web:8e9cfcd121a77c8e9710c0',
    messagingSenderId: '481479523905',
    projectId: 'aikya-73c23',
    authDomain: 'aikya-73c23.firebaseapp.com',
    storageBucket: 'aikya-73c23.firebasestorage.app',
    measurementId: 'G-ZJ03CD74GJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlbec46Lu8Oxs01BZETcGkm0s0y9ID6J4',
    appId: '1:481479523905:android:266147ecf55be44e9710c0',
    messagingSenderId: '481479523905',
    projectId: 'aikya-73c23',
    storageBucket: 'aikya-73c23.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB64NBYxaSapj8R7a56yV7e6S0MUJIgZYs',
    appId: '1:481479523905:web:8e9cfcd121a77c8e9710c0',
    messagingSenderId: '481479523905',
    projectId: 'aikya-73c23',
    authDomain: 'aikya-73c23.firebaseapp.com',
    storageBucket: 'aikya-73c23.firebasestorage.app',
    measurementId: 'G-ZJ03CD74GJ',
  );
}
