import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../../../core/theme/app_theme.dart';
import '../../../auth/presentation/providers/auth_provider.dart';
import '../../domain/models/payout_request_model.dart';
import '../providers/chef_provider.dart';

class PayoutRequestScreen extends StatefulWidget {
  final double availableBalance;
  const PayoutRequestScreen({super.key, required this.availableBalance});

  @override
  State<PayoutRequestScreen> createState() => _PayoutRequestScreenState();
}

class _PayoutRequestScreenState extends State<PayoutRequestScreen> {
  final _formKey = GlobalKey<FormState>();
  final TextEditingController _amountController = TextEditingController();
  final TextEditingController _bankNameController = TextEditingController();
  final TextEditingController _accountNoController = TextEditingController();
  final TextEditingController _ifscController = TextEditingController();

  void _submitRequest() async {
    if (_formKey.currentState!.validate()) {
      final chefProvider = Provider.of<ChefProvider>(context, listen: false);
      final authProvider = Provider.of<AuthProvider>(context, listen: false);
      final uid = authProvider.userProfile?['uid'] ?? '';

      if (uid.isNotEmpty && chefProvider.myKitchen != null) {
        final request = PayoutRequestModel(
          id: '', // Generated by Firestore
          chefId: uid,
          chefName: chefProvider.myKitchen!['chefName'] ?? '',
          amount: double.parse(_amountController.text.trim()),
          bankName: _bankNameController.text.trim(),
          accountNumber: _accountNoController.text.trim(),
          ifscCode: _ifscController.text.trim().toUpperCase(),
          status: 'pending',
          requestedAt: DateTime.now(),
        );

        try {
          await chefProvider.submitPayoutRequest(request.toMap());
          if (mounted) {
            Navigator.pop(context);
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(
                content: Text("Payout request submitted successfully!"),
                backgroundColor: AppTheme.secondaryColor,
              ),
            );
          }
        } catch (e) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text("Error: $e"), backgroundColor: AppTheme.errorColor),
          );
        }
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Request Payout"),
        backgroundColor: AppTheme.secondaryColor,
        foregroundColor: Colors.white,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24.0),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              _buildBalanceCard(),
              const SizedBox(height: 32),
              const Text("Withdrawal Details", style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              const SizedBox(height: 20),
              TextFormField(
                controller: _amountController,
                keyboardType: TextInputType.number,
                decoration: InputDecoration(
                  labelText: "Amount to Withdraw (₹)",
                  border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
                ),
                validator: (value) {
                  if (value == null || value.isEmpty) return "Required";
                  double? amt = double.tryParse(value);
                  if (amt == null) return "Invalid amount";
                  if (amt < 500) return "Minimum withdrawal is ₹500";
                  if (amt > widget.availableBalance) return "Insufficient balance";
                  return null;
                },
              ),
              const SizedBox(height: 20),
              TextFormField(
                controller: _bankNameController,
                decoration: InputDecoration(
                  labelText: "Bank Name",
                  border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
                ),
                validator: (value) => (value == null || value.isEmpty) ? "Required" : null,
              ),
              const SizedBox(height: 20),
              TextFormField(
                controller: _accountNoController,
                decoration: InputDecoration(
                  labelText: "Account Number",
                  border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
                ),
                validator: (value) => (value == null || value.isEmpty) ? "Required" : null,
              ),
              const SizedBox(height: 20),
              TextFormField(
                controller: _ifscController,
                decoration: InputDecoration(
                  labelText: "IFSC Code",
                  hintText: "e.g. SBIN0012345",
                  border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
                ),
                validator: (value) => (value == null || value.isEmpty) ? "Required" : null,
              ),
              const SizedBox(height: 40),
              Consumer<ChefProvider>(
                builder: (context, provider, child) {
                  return provider.isLoading
                      ? const Center(child: CircularProgressIndicator())
                      : ElevatedButton(
                          onPressed: _submitRequest,
                          style: ElevatedButton.styleFrom(backgroundColor: AppTheme.secondaryColor),
                          child: const Text("Submit Request"),
                        );
                },
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildBalanceCard() {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: AppTheme.secondaryColor.withValues(alpha: 0.1),
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: AppTheme.secondaryColor.withValues(alpha: 0.3)),
      ),
      child: Column(
        children: [
          Text("Available for Withdrawal", style: TextStyle(color: Colors.grey[700])),
          const SizedBox(height: 8),
          Text(
            "₹${widget.availableBalance.toStringAsFixed(0)}",
            style: const TextStyle(fontSize: 32, fontWeight: FontWeight.bold, color: AppTheme.secondaryColor),
          ),
        ],
      ),
    );
  }
}
